// AUTO-GENERATED by scripts/gen-glyphs.mjs — do not edit by hand.
// Source: Unicode Character Database (UnicodeData.txt, emoji-data.txt).
// Emoji-property codepoints are excluded. Regenerate with: npm run gen:misc-technical
import type { Glyph } from '../../types'

export const BLOCK_ELEMENTS: Glyph[] = [
  { c: "▀", cp: '2580', name: "Upper Half Block" },
  { c: "▁", cp: '2581', name: "Lower One Eighth Block" },
  { c: "▂", cp: '2582', name: "Lower One Quarter Block" },
  { c: "▃", cp: '2583', name: "Lower Three Eighths Block" },
  { c: "▄", cp: '2584', name: "Lower Half Block" },
  { c: "▅", cp: '2585', name: "Lower Five Eighths Block" },
  { c: "▆", cp: '2586', name: "Lower Three Quarters Block" },
  { c: "▇", cp: '2587', name: "Lower Seven Eighths Block" },
  { c: "█", cp: '2588', name: "Full Block" },
  { c: "▉", cp: '2589', name: "Left Seven Eighths Block" },
  { c: "▊", cp: '258A', name: "Left Three Quarters Block" },
  { c: "▋", cp: '258B', name: "Left Five Eighths Block" },
  { c: "▌", cp: '258C', name: "Left Half Block" },
  { c: "▍", cp: '258D', name: "Left Three Eighths Block" },
  { c: "▎", cp: '258E', name: "Left One Quarter Block" },
  { c: "▏", cp: '258F', name: "Left One Eighth Block" },
  { c: "▐", cp: '2590', name: "Right Half Block" },
  { c: "░", cp: '2591', name: "Light Shade" },
  { c: "▒", cp: '2592', name: "Medium Shade" },
  { c: "▓", cp: '2593', name: "Dark Shade" },
  { c: "▔", cp: '2594', name: "Upper One Eighth Block" },
  { c: "▕", cp: '2595', name: "Right One Eighth Block" },
  { c: "▖", cp: '2596', name: "Quadrant Lower Left" },
  { c: "▗", cp: '2597', name: "Quadrant Lower Right" },
  { c: "▘", cp: '2598', name: "Quadrant Upper Left" },
  { c: "▙", cp: '2599', name: "Quadrant Upper Left And Lower Left And Lower Right" },
  { c: "▚", cp: '259A', name: "Quadrant Upper Left And Lower Right" },
  { c: "▛", cp: '259B', name: "Quadrant Upper Left And Upper Right And Lower Left" },
  { c: "▜", cp: '259C', name: "Quadrant Upper Left And Upper Right And Lower Right" },
  { c: "▝", cp: '259D', name: "Quadrant Upper Right" },
  { c: "▞", cp: '259E', name: "Quadrant Upper Right And Lower Left" },
  { c: "▟", cp: '259F', name: "Quadrant Upper Right And Lower Left And Lower Right" },
]
