// AUTO-GENERATED by scripts/gen-glyphs.mjs — do not edit by hand.
// Source: Unicode Character Database (UnicodeData.txt, emoji-data.txt).
// Emoji-property codepoints are excluded. Regenerate with:
//   node scripts/gen-glyphs.mjs --range 2FF0-2FFB --export IDEOGRAPHIC_DESCRIPTION_CHARACTERS --out src/data/blocks/ideographicDescriptionCharacters.ts
import type { Glyph } from '../../types'

export const IDEOGRAPHIC_DESCRIPTION_CHARACTERS: Glyph[] = [
  { c: "⿰", cp: '2FF0', name: "Ideographic Description Character Left To Right" },
  { c: "⿱", cp: '2FF1', name: "Ideographic Description Character Above To Below" },
  { c: "⿲", cp: '2FF2', name: "Ideographic Description Character Left To Middle And Right" },
  { c: "⿳", cp: '2FF3', name: "Ideographic Description Character Above To Middle And Below" },
  { c: "⿴", cp: '2FF4', name: "Ideographic Description Character Full Surround" },
  { c: "⿵", cp: '2FF5', name: "Ideographic Description Character Surround From Above" },
  { c: "⿶", cp: '2FF6', name: "Ideographic Description Character Surround From Below" },
  { c: "⿷", cp: '2FF7', name: "Ideographic Description Character Surround From Left" },
  { c: "⿸", cp: '2FF8', name: "Ideographic Description Character Surround From Upper Left" },
  { c: "⿹", cp: '2FF9', name: "Ideographic Description Character Surround From Upper Right" },
  { c: "⿺", cp: '2FFA', name: "Ideographic Description Character Surround From Lower Left" },
  { c: "⿻", cp: '2FFB', name: "Ideographic Description Character Overlaid" },
]
