// AUTO-GENERATED by scripts/gen-glyphs.mjs — do not edit by hand.
// Source: Unicode Character Database (UnicodeData.txt, emoji-data.txt).
// Emoji-property codepoints are excluded. Regenerate with:
//   node scripts/gen-glyphs.mjs --range 2440-245F --export OCR --out src/data/blocks/ocr.ts
import type { Glyph } from '../../types'

export const OCR: Glyph[] = [
  { c: "⑀", cp: '2440', name: "OCR Hook" },
  { c: "⑁", cp: '2441', name: "OCR Chair" },
  { c: "⑂", cp: '2442', name: "OCR Fork" },
  { c: "⑃", cp: '2443', name: "OCR Inverted Fork" },
  { c: "⑄", cp: '2444', name: "OCR Belt Buckle" },
  { c: "⑅", cp: '2445', name: "OCR Bow Tie" },
  { c: "⑆", cp: '2446', name: "OCR Branch Bank Identification" },
  { c: "⑇", cp: '2447', name: "OCR Amount Of Check" },
  { c: "⑈", cp: '2448', name: "OCR Dash" },
  { c: "⑉", cp: '2449', name: "OCR Customer Account Number" },
  { c: "⑊", cp: '244A', name: "OCR Double Backslash" },
]
