#!/usr/bin/env node
// Generate glyph records for a Unicode block straight from the official
// Unicode Character Database, so names/codepoints are never hand-typed.
//
// Usage:
//   node scripts/gen-glyphs.mjs --range 2300-23FF --cat misc-technical \
//        --export MISC_TECHNICAL --out src/data/blocks/miscTechnical.ts
//
// Flags:
//   --range A-B     inclusive codepoint range in hex (e.g. 2300-23FF)
//   --cat  slug     category slug written to every record (default: misc)
//   --export NAME   exported const name (default: BLOCK)
//   --out  path     write a TS module here (omit to print to stdout)
//   --json          emit JSON instead of a TS module
//   --refresh       ignore the local cache and re-download UnicodeData.txt
//
// The UCD is cached under scripts/.cache/ so repeat runs work offline.

import { mkdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')
const CACHE = resolve(HERE, '.cache', 'UnicodeData.txt')
const UCD_URL = 'https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt'

// General categories that don't render as a standalone printable glyph.
const SKIP_CATEGORIES = new Set([
  'Cc', 'Cf', 'Cs', 'Co', 'Cn', // control / format / surrogate / private / unassigned
  'Zl', 'Zp', 'Zs',             // line / paragraph / space separators
  'Mn', 'Mc', 'Me',             // combining marks (need a base character)
])

// Tokens kept verbatim when title-casing an ALL-CAPS Unicode name.
const ACRONYMS = new Set([
  'APL', 'AC', 'DC', 'TV', 'AM', 'FM', 'ID', 'OCR', 'DVD', 'CD',
  'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X',
])

function parseArgs(argv) {
  const out = { cat: 'misc', export: 'BLOCK', json: false, refresh: false }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--json') out.json = true
    else if (a === '--refresh') out.refresh = true
    else if (a === '--range') out.range = argv[++i]
    else if (a === '--cat') out.cat = argv[++i]
    else if (a === '--export') out.export = argv[++i]
    else if (a === '--out') out.out = argv[++i]
    else throw new Error(`unknown flag: ${a}`)
  }
  if (!out.range) throw new Error('missing --range (e.g. --range 2300-23FF)')
  const [lo, hi] = out.range.split('-').map((h) => parseInt(h, 16))
  if (!Number.isInteger(lo) || !Number.isInteger(hi) || lo > hi) {
    throw new Error(`bad --range: ${out.range}`)
  }
  out.lo = lo
  out.hi = hi
  return out
}

async function loadUCD(refresh) {
  if (!refresh && existsSync(CACHE)) return readFileSync(CACHE, 'utf8')
  process.stderr.write(`fetching ${UCD_URL} …\n`)
  const res = await fetch(UCD_URL)
  if (!res.ok) throw new Error(`download failed: ${res.status} ${res.statusText}`)
  const text = await res.text()
  mkdirSync(dirname(CACHE), { recursive: true })
  writeFileSync(CACHE, text)
  return text
}

// "DIAMETER SIGN" -> "Diameter Sign"; preserves acronyms and hyphen segments.
function titleCase(name) {
  return name
    .split(' ')
    .map((word) =>
      word
        .split('-')
        .map((seg) => (ACRONYMS.has(seg) ? seg : seg.charAt(0) + seg.slice(1).toLowerCase()))
        .join('-'),
    )
    .join(' ')
}

function collect(ucd, { lo, hi, cat }) {
  const rows = []
  for (const line of ucd.split('\n')) {
    if (!line) continue
    const f = line.split(';')
    const cp = parseInt(f[0], 16)
    if (cp < lo || cp > hi) continue
    const name = f[1]
    const gc = f[2]
    if (name.startsWith('<')) continue // control chars and algorithmic range markers
    if (SKIP_CATEGORIES.has(gc)) continue
    rows.push({
      c: String.fromCodePoint(cp),
      cp: f[0].toUpperCase(),
      name: titleCase(name),
      cat,
    })
  }
  return rows
}

function toModule(rows, exportName) {
  const body = rows
    .map((r) => `  { c: ${JSON.stringify(r.c)}, cp: '${r.cp}', name: ${JSON.stringify(r.name)}, cat: '${r.cat}' },`)
    .join('\n')
  return (
    `// AUTO-GENERATED by scripts/gen-glyphs.mjs — do not edit by hand.\n` +
    `// Source: Unicode Character Database (UnicodeData.txt).\n` +
    `// Regenerate with: npm run gen:misc-technical\n` +
    `import type { Glyph } from '../../types'\n\n` +
    `export const ${exportName}: Glyph[] = [\n${body}\n]\n`
  )
}

const opts = parseArgs(process.argv.slice(2))
const ucd = await loadUCD(opts.refresh)
const rows = collect(ucd, opts)

const output = opts.json ? JSON.stringify(rows, null, 2) + '\n' : toModule(rows, opts.export)
if (opts.out) {
  const dest = resolve(ROOT, opts.out)
  mkdirSync(dirname(dest), { recursive: true })
  writeFileSync(dest, output)
  process.stderr.write(`wrote ${rows.length} glyphs → ${opts.out}\n`)
} else {
  process.stdout.write(output)
  process.stderr.write(`${rows.length} glyphs\n`)
}
